
services:
  veld_step_1_preprocess:
    build: ./code/step_1/
    command: python preprocess.py
    working_dir: /veld/code/
    volumes:
      - ./data/input/texts/:/veld/input/
      - ./data/input/texts/:/veld/output/
      - ./code/step_1/:/veld/code/
